development:
  adapter: postgresql
  encoding: utf8
  database: pathology
  pool: 5
  username: path
  password: pass123

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: path
  password: pass123

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5 
  username: path
  password: pass123

cucumber:
  <<: *TEST